name: "Cleanup Samples"
description: "Deletes statements related to samples."

inputs:
  melos-yaml-path:
    description: "Path to the melos.yaml file"
    default: "melos.yaml"
  vscode-launch-json-path:
    description: "Path to the launch.yaml file"
    default: ".vscode/launch.json"

runs:
  using: "composite"
  steps:
    - name: Remove samples from melos.yaml
      run: |
        yq eval 'del(.packages[] | select(. == "packages/samples/*" or . == "samples/*"))' ${{ inputs.melos-yaml-path }} > ${{ inputs.melos-yaml-path }}.new
        
        # Keep empty lines
        diff -U0 -w -b --ignore-blank-lines ${{ inputs.melos-yaml-path }} ${{ inputs.melos-yaml-path }}.new > ${{ inputs.melos-yaml-path }}.diff || true
        patch ${{ inputs.melos-yaml-path }} < ${{ inputs.melos-yaml-path }}.diff
        rm ${{ inputs.melos-yaml-path }}.{new,diff}
      shell: bash

    - name: Strip comments from launch.json
      run: strip-json-comments ${{ inputs.vscode-launch-json-path }} > ${{ inputs.vscode-launch-json-path }}.temp
      shell: sh

    - name: Remove samples configurations from launch.json
      run: >
        jq -n -f ${{ inputs.vscode-launch-json-path }}.temp |
        jq '
        .configurations |= map(select(.cwd | strings | startswith("samples/") | not))
        '
        > ${{ inputs.vscode-launch-json-path }}
      shell: sh

    - name: Remove temp file
      run: rm ${{ inputs.vscode-launch-json-path }}.temp
      shell: sh
