name: "Fill project name"
description: "Fill project name of melos.yaml and pubspec.yaml with the repository name"

runs:
  using: "composite"
  steps:
    - name: Convert repository name to snake_case
      id: convert_name
      shell: bash
      run: |
        SNAKE_CASE=$(echo "${{ github.event.repository.name }}" | sed -r 's/([a-z0-9])([A-Z])/\1_\L\2/g' | tr '-' '_' | tr '[:upper:]' '[:lower:]')
        echo "repository_name=$SNAKE_CASE" >> $GITHUB_OUTPUT

    - name: Fill the project name
      uses: mikefarah/yq@f15500b20a1c991c8729870ba60a4dc3524b6a94 # v4.44.2
      with:
        cmd: |
          yq '.name = "${{ steps.convert_name.outputs.repository_name }}"' melos.yaml > melos.yaml.new
          yq '.name = "${{ steps.convert_name.outputs.repository_name }}"' pubspec.yaml > pubspec.yaml.new

    - name: Keep empty lines
      # NOTE: https://github.com/mikefarah/yq/issues/515
      run: |
        diff -U0 -w -b --ignore-blank-lines melos.yaml melos.yaml.new > melos.yaml.diff || true
        diff -U0 -w -b --ignore-blank-lines pubspec.yaml pubspec.yaml.new > pubspec.yaml.diff || true
        patch melos.yaml < melos.yaml.diff
        patch pubspec.yaml < pubspec.yaml.diff
        rm melos.yaml.{new,diff} pubspec.yaml.{new,diff}
      shell: bash
